application: yourappnamehere
version: 1
runtime: python
api_version: 1

handlers:
# - url: /
#   static_files: public/index.html
#   upload: public/index.html  
- url: /(.*\.(js|css|png|gif|jpg|ico))
  static_files: public/\1
  upload: public/(.*\.(js|css|png|gif|jpg))
- url: .*
  script: main.py
